version: '3.8'

services:
  jesterquizz-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jesterquizz-api
    restart: unless-stopped
    ports:
      - "8082:8080"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      
volumes:
  db_data:
